/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Results */
        get: operations["list_results_api_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_api_results__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies */
        get: operations["list_strategies_api_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Strategies */
        get: operations["compare_strategies_api_strategies_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strategy */
        get: operations["get_strategy_api_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ideas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ideas */
        get: operations["list_ideas_api_ideas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ideas/{idea_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Idea */
        get: operations["get_idea_api_ideas__idea_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfo/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wfo */
        get: operations["get_wfo_api_wfo__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Optimize */
        get: operations["get_optimize_api_optimize__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Backtest
         * @description forge backtest run をサブプロセス実行し、最新の run_id を返す。
         */
        post: operations["run_backtest_api_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Live
         * @description live summary が存在する戦略 ID 一覧を返す。
         *
         *     フロントの「Live」タブ表示判定に使う。
         */
        get: operations["list_live_api_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Live
         * @description 指定戦略の live summary + trades と、期間整合した backtest aligned/diff を返す。
         */
        get: operations["get_live_api_live__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spa Fallback
         * @description SPA ルート対応: /api 配下以外で実ファイルがあればそれを返し、
         *     無ければ index.html を返して history mode の直アクセス・リロードに対応する。
         */
        get: operations["spa_fallback__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BacktestDetail
         * @description ``GET /api/results/{run_id}`` 詳細レスポンス。
         *
         *     フィールドは ``services.backtest.build_detail`` の出力構造に対応する。
         *     ``metrics`` / ``is_metrics`` / ``oos_metrics`` / ``monthly_returns``
         *     などの巨大ネストは ``Any`` で受け、``extra="allow"`` で将来追加にも追従。
         *
         *     ``regime_series`` / ``regime_breakdown`` は条件付きで含まれるフィールド。
         *     services 層が結果 dict に含めなかった場合は ``None`` のままにし、
         *     ``_serialize_with_optional_regime`` で JSON レスポンスから完全に除外する
         *     （``"regime_*": null`` がレスポンスに混入することを防ぐ）。
         */
        BacktestDetail: {
            /** Run Id */
            run_id: string;
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Name */
            strategy_name: string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /**
             * Timeframe
             * @default 1d
             */
            timeframe: string;
            /**
             * Run At
             * @default
             */
            run_at: string;
            /**
             * @default {
             *       "start": "",
             *       "end": ""
             *     }
             */
            period: components["schemas"]["Period"];
            /**
             * @default {
             *       "dates": [],
             *       "values": []
             *     }
             */
            equity: components["schemas"]["BacktestEquityCurve"];
            /**
             * Drawdown
             * @default []
             */
            drawdown: number[];
            /**
             * Daily Returns
             * @default []
             */
            daily_returns: number[];
            /**
             * Buy Hold Equity
             * @default []
             */
            buy_hold_equity: number[];
            /**
             * @default {
             *       "index": -1
             *     }
             */
            is_cutoff: components["schemas"]["IsCutoff"];
            /**
             * Metrics
             * @default {}
             */
            metrics: {
                [key: string]: unknown;
            };
            /** Is Metrics */
            is_metrics?: {
                [key: string]: unknown;
            } | null;
            /** Oos Metrics */
            oos_metrics?: {
                [key: string]: unknown;
            } | null;
            /**
             * Monthly Returns
             * @default {}
             */
            monthly_returns: {
                [key: string]: (number | null)[];
            };
            /**
             * Trades
             * @default []
             */
            trades: components["schemas"]["Trade"][];
            /**
             * Benchmark Annual Returns
             * @default {}
             */
            benchmark_annual_returns: {
                [key: string]: number;
            };
            regime_series?: components["schemas"]["RegimeSeries"] | null;
            /** Regime Breakdown */
            regime_breakdown?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * BacktestEquityCurve
         * @description ``BacktestDetail.equity``: dates / values の配列ペア。
         */
        BacktestEquityCurve: {
            /**
             * Dates
             * @default []
             */
            dates: string[];
            /**
             * Values
             * @default []
             */
            values: number[];
        } & {
            [key: string]: unknown;
        };
        /**
         * BacktestSummary
         * @description ``GET /api/results`` リストの 1 件。
         */
        BacktestSummary: {
            /** Run Id */
            run_id: string;
            /** Strategy Id */
            strategy_id?: string | null;
            /** Symbol */
            symbol?: string | null;
            /** Run At */
            run_at?: string | null;
            /** Sharpe Ratio */
            sharpe_ratio?: number | null;
            /** Total Return Pct */
            total_return_pct?: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct?: number | null;
            /** Total Trades */
            total_trades?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ComparisonEquityCurve
         * @description ``StrategyComparison.equity`` の構造（dates / values の配列ペア）。
         */
        ComparisonEquityCurve: {
            /**
             * Dates
             * @default []
             */
            dates: string[];
            /**
             * Values
             * @default []
             */
            values: number[];
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Idea
         * @description ideas.json の 1 アイデア。
         *
         *     フィールドは ideas.json のキーをそのまま反映。未知フィールドは
         *     透過するため ``extra="allow"`` を設定（運用での互換性維持）。
         */
        Idea: {
            /** Idea Id */
            idea_id?: string | null;
            /** Title */
            title?: string | null;
            /** Status */
            status?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Notes */
            notes?: string | null;
            /** Linked Strategies */
            linked_strategies?: string[] | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * IsCutoff
         * @description ``BacktestDetail.is_cutoff``: IS / OOS の境界位置。
         */
        IsCutoff: {
            /** Date */
            date?: string | null;
            /**
             * Index
             * @default -1
             */
            index: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveAligned
         * @description ``LiveDetail.backtest.aligned``: 期間整合済みのバックテスト集計値。
         */
        LiveAligned: {
            /** Total Trades */
            total_trades: number;
            /** Win Rate Pct */
            win_rate_pct: number;
            /** Profit Factor */
            profit_factor: number;
            /** Max Drawdown Pct */
            max_drawdown_pct: number;
            /** Net Pnl */
            net_pnl: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveBacktest
         * @description ``LiveDetail.backtest``: 対応 backtest の run_id + period + aligned 集計。
         */
        LiveBacktest: {
            /** Run Id */
            run_id: string;
            period: components["schemas"]["LivePeriod"];
            aligned?: components["schemas"]["LiveAligned"] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveDetail
         * @description ``GET /api/live/{strategy_id}`` 詳細レスポンス。
         *
         *     live summary + 正規化済み trades と、それに整合する backtest aligned/diff、
         *     計算できなかった理由を伝える warnings 配列を返す。
         */
        LiveDetail: {
            /** Strategy Id */
            strategy_id: string;
            live: components["schemas"]["LiveSection"];
            backtest?: components["schemas"]["LiveBacktest"] | null;
            diff?: components["schemas"]["LiveDiff"] | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveDiff
         * @description ``LiveDetail.diff``: live − aligned のメトリクス差分。
         */
        LiveDiff: {
            /** Total Trades */
            total_trades?: number | null;
            /** Win Rate Pct */
            win_rate_pct?: number | null;
            /** Profit Factor */
            profit_factor?: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct?: number | null;
            /** Net Pnl */
            net_pnl?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveListItem
         * @description ``GET /api/live`` リストの 1 件。
         */
        LiveListItem: {
            /** Strategy Id */
            strategy_id: string;
            /** Has Summary */
            has_summary: boolean;
            /** Has Trades */
            has_trades: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * LivePeriod
         * @description ``LiveDetail.live.period`` / ``LiveDetail.backtest.period``。
         */
        LivePeriod: {
            /** Start */
            start: string;
            /** End */
            end: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveSection
         * @description ``LiveDetail.live`` セクション (summary / trades / period)。
         */
        LiveSection: {
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /**
             * Trades
             * @default []
             */
            trades: components["schemas"]["LiveTrade"][];
            period?: components["schemas"]["LivePeriod"] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveTrade
         * @description live trades JSON を正規化した 1 件。
         */
        LiveTrade: {
            /**
             * Trade Id
             * @default
             */
            trade_id: string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /** Side */
            side: string;
            /** Entry At */
            entry_at: string;
            /** Exit At */
            exit_at: string;
            /**
             * Qty
             * @default 0
             */
            qty: number;
            /**
             * Entry Price
             * @default 0
             */
            entry_price: number;
            /**
             * Exit Price
             * @default 0
             */
            exit_price: number;
            /**
             * Net Pnl
             * @default 0
             */
            net_pnl: number;
            /** Return Pct */
            return_pct?: number | null;
            /** Exit Reason */
            exit_reason?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * OptimizationHistoryEntry
         * @description ``StrategyDetail.optimization_history`` の 1 件。
         */
        OptimizationHistoryEntry: {
            /** Trial */
            trial: number;
            /** Best Sharpe */
            best_sharpe?: number | null;
            /** Run At */
            run_at?: string | null;
            /** N Trials */
            n_trials?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * OptimizeResult
         * @description ``GET /api/optimize/{strategy_id}`` レスポンス。
         */
        OptimizeResult: {
            /** Strategy Id */
            strategy_id: string;
            /**
             * Run At
             * @default
             */
            run_at: string;
            /**
             * Metric Name
             * @default sharpe_ratio
             */
            metric_name: string;
            /**
             * Best Metric
             * @default 0
             */
            best_metric: number;
            /**
             * Trials
             * @default []
             */
            trials: components["schemas"]["OptimizeTrial"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * OptimizeTrial
         * @description 1 試行のパラメータと評価値。
         *
         *     ``routers/optimize.py::_parse_trial`` が組み立てる dict の構造：
         *     ``{"params": {...}, "metric": float, "pass": bool, "metrics": {...}}``。
         *
         *     ``pass`` キーは Python 予約語のため明示フィールドとして宣言できない。
         *     レスポンス互換性のため ``extra="allow"`` で透過的に保持する。
         */
        OptimizeTrial: {
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: number;
            };
            /**
             * Metric
             * @default 0
             */
            metric: number;
            /**
             * Metrics
             * @default {}
             */
            metrics: {
                [key: string]: number;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * Period
         * @description ``BacktestDetail.period``: equity 期間の YYYY-MM 表記。
         */
        Period: {
            /**
             * Start
             * @default
             */
            start: string;
            /**
             * End
             * @default
             */
            end: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * RegimeSeries
         * @description HMM レジームステート時系列。``services.shape_regime_series`` で正規化済み。
         *
         *     すべてのフィールドは ``services`` 側で検証済み（dates と states の長さ一致、
         *     states は int リスト等）なので、Pydantic 側では shape のみを担保する。
         */
        RegimeSeries: {
            /** Dates */
            dates: string[];
            /** States */
            states: number[];
            /** N States */
            n_states: number;
            /** Label Names */
            label_names?: {
                [key: string]: string;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** RunBacktestRequest */
        RunBacktestRequest: {
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
        };
        /** RunBacktestResponse */
        RunBacktestResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
        };
        /**
         * StrategyComparison
         * @description ``GET /api/strategies/compare`` の 1 件。equity / 比較指標を含む。
         */
        StrategyComparison: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /**
             * Total Return Pct
             * @default 0
             */
            total_return_pct: number;
            /**
             * Cagr Pct
             * @default 0
             */
            cagr_pct: number;
            /**
             * Sharpe Ratio
             * @default 0
             */
            sharpe_ratio: number;
            /**
             * Sortino Ratio
             * @default 0
             */
            sortino_ratio: number;
            /**
             * Max Drawdown Pct
             * @default 0
             */
            max_drawdown_pct: number;
            /**
             * Win Rate Pct
             * @default 0
             */
            win_rate_pct: number;
            /**
             * Profit Factor
             * @default 0
             */
            profit_factor: number;
            /**
             * Total Trades
             * @default 0
             */
            total_trades: number;
            /**
             * Is Baseline
             * @default false
             */
            is_baseline: boolean;
            /**
             * @default {
             *       "dates": [],
             *       "values": []
             *     }
             */
            equity: components["schemas"]["ComparisonEquityCurve"];
            /**
             * Daily Returns
             * @default []
             */
            daily_returns: number[];
        } & {
            [key: string]: unknown;
        };
        /**
         * StrategyDetail
         * @description ``GET /api/strategies/{strategy_id}`` 詳細レスポンス。
         *
         *     戦略定義（parameters / indicators / variables / *_conditions /
         *     risk_management / regime_config）と、バックテスト履歴 / 最適化履歴を返す。
         */
        StrategyDetail: {
            /** Strategy Id */
            strategy_id: string;
            /** Name */
            name: string;
            /**
             * Parameters
             * @default {}
             */
            parameters: {
                [key: string]: unknown;
            };
            /**
             * Indicators
             * @default []
             */
            indicators: unknown[];
            /**
             * Variables
             * @default []
             */
            variables: unknown[];
            /** Entry Conditions */
            entry_conditions?: unknown;
            /** Exit Conditions */
            exit_conditions?: unknown;
            /** Risk Management */
            risk_management?: unknown;
            /** Regime Config */
            regime_config?: unknown;
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["StrategyResultEntry"][];
            /**
             * Optimization History
             * @default []
             */
            optimization_history: components["schemas"]["OptimizationHistoryEntry"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * StrategyResultEntry
         * @description ``StrategyDetail.results`` の 1 件（バックテスト履歴サマリ）。
         */
        StrategyResultEntry: {
            /** Run Id */
            run_id: string;
            /** Symbol */
            symbol?: string | null;
            /** Sharpe */
            sharpe?: number | null;
            /** Return Pct */
            return_pct?: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct?: number | null;
            /** Total Trades */
            total_trades?: number | null;
            /** Run At */
            run_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * StrategySummary
         * @description ``GET /api/strategies`` リストの 1 件。
         */
        StrategySummary: {
            /** Strategy Id */
            strategy_id: string;
            /** Name */
            name: string;
            /** Symbol */
            symbol?: string | null;
            /** Timeframe */
            timeframe?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Target Symbols
             * @default []
             */
            target_symbols: string[];
            /** Latest Sharpe */
            latest_sharpe?: number | null;
            /** Latest Return Pct */
            latest_return_pct?: number | null;
            /** Latest Max Drawdown Pct */
            latest_max_drawdown_pct?: number | null;
            /** Latest Profit Factor */
            latest_profit_factor?: number | null;
            /** Latest Win Rate Pct */
            latest_win_rate_pct?: number | null;
            /** Latest Total Trades */
            latest_total_trades?: number | null;
            /** Last Run At */
            last_run_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Trade
         * @description ``BacktestDetail.trades`` の 1 件。
         */
        Trade: {
            /** Id */
            id: number | string;
            /** Direction */
            direction: string;
            /**
             * Entry Date
             * @default
             */
            entry_date: string;
            /**
             * Exit Date
             * @default
             */
            exit_date: string;
            /**
             * Entry Price
             * @default 0
             */
            entry_price: number;
            /**
             * Return Pct
             * @default 0
             */
            return_pct: number;
            /**
             * Pnl
             * @default 0
             */
            pnl: number;
            /**
             * Holding Days
             * @default 0
             */
            holding_days: number;
            /**
             * Mae Pct
             * @default 0
             */
            mae_pct: number;
            /**
             * Mfe Pct
             * @default 0
             */
            mfe_pct: number;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WFOResponse
         * @description ``GET /api/wfo/{strategy_id}`` レスポンス。
         */
        WFOResponse: {
            /** Strategy Id */
            strategy_id: string;
            /**
             * Strategy Name
             * @default
             */
            strategy_name: string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /**
             * Windows
             * @default []
             */
            windows: components["schemas"]["WFOWindow"][];
            /**
             * Composite Equity
             * @default []
             */
            composite_equity: number[];
            /**
             * Composite Dates
             * @default []
             */
            composite_dates: string[];
        } & {
            [key: string]: unknown;
        };
        /**
         * WFOWindow
         * @description 1 ウィンドウの IS / OOS 評価値。
         *
         *     ``pass`` キーは Python 予約語のため明示フィールドとして宣言できない。
         *     レスポンス互換性のため ``extra="allow"`` で透過的に保持する。
         */
        WFOWindow: {
            /** Id */
            id: number;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Is Start
             * @default
             */
            is_start: string;
            /**
             * Is End
             * @default
             */
            is_end: string;
            /**
             * Oos Start
             * @default
             */
            oos_start: string;
            /**
             * Oos End
             * @default
             */
            oos_end: string;
            /**
             * Is Sharpe
             * @default 0
             */
            is_sharpe: number;
            /**
             * Oos Sharpe
             * @default 0
             */
            oos_sharpe: number;
            /**
             * Is Return
             * @default 0
             */
            is_return: number;
            /**
             * Oos Return
             * @default 0
             */
            oos_return: number;
            /**
             * Oos Is Ratio
             * @default 0
             */
            oos_is_ratio: number;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: number;
            };
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_results_api_results_get: {
        parameters: {
            query?: {
                strategy_id?: string | null;
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_results__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategySummary"][];
                };
            };
        };
    };
    compare_strategies_api_strategies_compare_get: {
        parameters: {
            query: {
                /** @description カンマ区切りの strategy_id */
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyComparison"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_api_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ideas_api_ideas_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Idea"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_idea_api_ideas__idea_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idea_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Idea"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wfo_api_wfo__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WFOResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_optimize_api_optimize__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_backtest_api_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunBacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_live_api_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveListItem"][];
                };
            };
        };
    };
    get_live_api_live__strategy_id__get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    spa_fallback__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
