/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Results */
        get: operations["list_results_api_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_api_results__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies */
        get: operations["list_strategies_api_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Strategies */
        get: operations["compare_strategies_api_strategies_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/sparkline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Strategy Sparkline
         * @description Browse 行ホバー用の軽量 sparkline (issue #387)。
         *
         *     最新 run の equity をダウンサンプルした値だけを返す。従来はフロントが
         *     「run 一覧 → 約 2MB のフル詳細」を 2 連 fetch していた。
         */
        get: operations["get_strategy_sparkline_api_strategies__strategy_id__sparkline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strategy */
        get: operations["get_strategy_api_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Strategy Parameters
         * @description 編集済みパラメータを戦略定義へ書き戻す（destructive・UI 側で確認必須）。
         *
         *     visualizer はファイル・DB を直接書かず、パラメータ差し替え済みの一時
         *     JSON を ``forge strategy save --force`` に渡して登録を委譲する
         *     （single-writer 維持。スキーマ検証は forge 側 Pydantic が SSoT で、
         *     エラーはそのまま表面化させる）。
         */
        post: operations["save_strategy_parameters_api_strategies__strategy_id__parameters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate Strategy
         * @description 既存戦略を別 ID で複製して新規登録する（vis#301・複製ベースの新規作成）。
         *
         *     visualizer はファイル・DB を直接書かず、strategy_id を差し替えた一時 JSON を
         *     ``forge strategy save``（--force **なし**）へ委譲する（single-writer 維持）。
         *     --force を付けないため ID 衝突は forge 側でも拒否され、既存戦略は
         *     上書きされない。事前チェックで既知の衝突は 409 で返す（レース時は forge の
         *     拒否が 500 として表面化する）。
         */
        post: operations["duplicate_strategy_api_strategies__strategy_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ideas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ideas */
        get: operations["list_ideas_api_ideas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ideas/{idea_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Idea */
        get: operations["get_idea_api_ideas__idea_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfo/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wfo */
        get: operations["get_wfo_api_wfo__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Optimize */
        get: operations["get_optimize_api_optimize__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Backtest
         * @description forge backtest run をサブプロセス実行し、run_id と実行ログ末尾を返す。
         */
        post: operations["run_backtest_api_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description 新しい順のジョブサマリ一覧。
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description ジョブを起動し、実行を待たずにサマリを返す。
         *
         *     ``parameters`` 指定時（チューニング実行 #293）は、元の戦略定義の
         *     parameters だけを差し替えた一時ファイルを作り ``--strategy-file`` で
         *     実行する。一時ファイルはジョブ終了時に JobManager が削除する。
         */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description ジョブ詳細（ログ末尾・結果要約付き）。
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description ジョブをキャンセルする（終了済みなら現状を返すだけ）。
         */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Events
         * @description ジョブ進捗の SSE ストリーム。
         *
         *     snapshot（現在の全ログ + 状態）→ log（新規行）→ status（終了）を配信し、
         *     terminal 到達で接続を閉じる。待ちの間はハートビートコメントを送る。
         */
        get: operations["job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Live
         * @description live サマリを持つ戦略 / portfolio の一覧を返す。
         *
         *     フロントの「Live」タブ表示判定に使う。trade 単位（``kind="strategy"``）と
         *     combine の position ベース（``kind="position"``）を両方含める。
         */
        get: operations["list_live_api_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Live
         * @description 指定戦略の live summary + trades と、期間整合した backtest aligned/diff を返す。
         */
        get: operations["get_live_api_live__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Live Job
         * @description ライブ実績の一括更新（forge `live refresh`）ジョブを起動する。
         *
         *     sync-events（SSH）・データ取得・DB 書き込みを伴う書き込み系のため、
         *     非 loopback 公開中は 403 で拒否する（routers/data.py と同じ方針）。
         *     forge 未導入はジョブを積んでから失敗させず、起動前に fail-fast する。
         *     replay パラメータは forge.yaml の `live.replay` が SSoT（リクエストに無い）。
         */
        post: operations["create_live_job_api_live_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/historical/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Historical
         * @description 指定 symbol × interval の OHLC ローソク足を返す。
         *
         *     404: historical_dir 不在 or parquet ファイル不在
         *     400: symbol が不正、または start/end の形式不正
         */
        get: operations["get_historical_api_historical__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Data Job
         * @description データ取得（fetch）/ 一括差分更新（update）ジョブを起動する。
         *
         *     ネットワークアクセスとファイル生成を伴う書き込み系のため、非 loopback
         *     公開中は 403 で拒否する（routers/agent.py と同じ方針）。forge 未導入は
         *     ジョブを積んでから失敗させず、起動前に fail-fast する。
         */
        post: operations["create_data_job_api_data_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pine/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Pine */
        post: operations["generate_pine_api_pine__strategy_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pine/{strategy_id}/support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pine Support
         * @description 生成前の非対応指標チェック（issue #488）。
         *
         *     対応表は `analyze indicator list --json` に委譲する（SSoT は forge。
         *     visualizer に対応指標をハードコードすると forge 側の追加・変更とずれる）。
         *     対応表に無い指標型は「非対応」として警告に倒す — 判定できないものを
         *     「対応」と見せると TradingView へ持ち出してから動かない事故になる。
         *     参照専用のため local_write ガードは掛けない。
         */
        get: operations["pine_support_api_pine__strategy_id__support_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/orphan-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orphan Runs */
        get: operations["list_orphan_runs_api_maintenance_orphan_runs_get"];
        put?: never;
        post?: never;
        /** Prune Orphan Runs */
        delete: operations["prune_orphan_runs_api_maintenance_orphan_runs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/backends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Agent Backends
         * @description エージェントバックエンドの検出結果を返す（GUI の選択肢構築用）。
         *
         *     無効時（非 loopback 公開中）は CLI 検出・``--version`` 実行を一切行わず
         *     403 を返す（設計: docs/superpowers/specs/2026-08-02-agent-develop-design.md
         *     セキュリティ設計 #3）。検出結果の開示自体が任意コード実行の下調べに
         *     使われうるため、POST と同様にエンドポイント冒頭で遮断する。
         */
        get: operations["list_agent_backends_api_agent_backends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Agent Job
         * @description クイック戦略開発ジョブを起動する。
         *
         *     実行前に「機能有効・forge 導入済み・agent CLI 導入済み・（派生時は）
         *     派生元の存在」を確認して fail-fast する（エージェント起動後に判明すると
         *     原因がログの奥に埋まる）。
         */
        post: operations["create_agent_job_api_agent_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Setup Status */
        get: operations["get_setup_status_api_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Versions */
        get: operations["get_versions_api_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/forge/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Forge
         * @description ``alpha-forge self update --yes`` をジョブとして起動する。
         *
         *     ゲートは既存の ``local_write_enabled`` を再利用する（routers/data.py・
         *     routers/pine.py と同じ方針）。パッケージ更新は「書き込み系ローカル限定
         *     機能」そのもので、新しいフラグを足す理由がない。
         */
        post: operations["update_forge_api_versions_forge_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/strike/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Strike
         * @description alpha-strike は GUI から更新しない（明示的に 400 で断る）。
         *
         *     ルート自体を生やさず 404 にすると「まだ実装されていないのか、
         *     意図的に無いのか」がクライアントから区別できない。
         */
        post: operations["update_strike_api_versions_strike_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/visualizer/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Visualizer
         * @description 自分自身を pip / uv で更新するジョブを起動する。
         *
         *     実行中プロセスを差し替えるため、事前ガードを 4 つ通す。1 つでも欠けたら
         *     ジョブを積まずに 409 で断る（積んでから失敗させると、原因がログの奥に
         *     埋まったうえに中途半端な状態が残りうる）。
         */
        post: operations["update_visualizer_api_versions_visualizer_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentBackendInfo
         * @description エージェントバックエンド 1 件の検出結果。
         */
        AgentBackendInfo: {
            /**
             * Id
             * @enum {string}
             */
            id: "claude" | "codex";
            /** Available */
            available: boolean;
            /** Version */
            version: string | null;
        };
        /**
         * AgentBackendsResponse
         * @description 検出結果と機能の有効状態。enabled=False は非 loopback 公開中。
         */
        AgentBackendsResponse: {
            /** Enabled */
            enabled: boolean;
            /** Backends */
            backends: components["schemas"]["AgentBackendInfo"][];
            /**
             * Default Max Turns
             * @default 100
             */
            default_max_turns: number;
            /**
             * Max Max Turns
             * @default 500
             */
            max_max_turns: number;
        };
        /**
         * AuthCheck
         * @description 認証状態。ローカル情報の表示のみ（GUI から auth login は起動しない）。
         */
        AuthCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "attention" | "unknown";
            /** Logged In */
            logged_in?: boolean | null;
            /** Plan Type */
            plan_type?: string | null;
        };
        /**
         * BacktestDetail
         * @description ``GET /api/results/{run_id}`` 詳細レスポンス。
         *
         *     フィールドは ``services.backtest.build_detail`` の出力構造に対応する。
         *     ``metrics`` / ``is_metrics`` / ``oos_metrics`` / ``monthly_returns``
         *     などの巨大ネストは ``Any`` で受け、``extra="allow"`` で将来追加にも追従。
         *
         *     ``regime_series`` / ``regime_breakdown`` は条件付きで含まれるフィールド。
         *     services 層が結果 dict に含めなかった場合は ``None`` のままにし、
         *     ``_serialize_with_optional_regime`` で JSON レスポンスから完全に除外する
         *     （``"regime_*": null`` がレスポンスに混入することを防ぐ）。
         */
        BacktestDetail: {
            /** Run Id */
            run_id: string;
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Name */
            strategy_name: string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /**
             * Timeframe
             * @default 1d
             */
            timeframe: string;
            /**
             * Run At
             * @default
             */
            run_at: string;
            /**
             * @default {
             *       "start": "",
             *       "end": ""
             *     }
             */
            period: components["schemas"]["Period"];
            /**
             * @default {
             *       "dates": [],
             *       "values": []
             *     }
             */
            equity: components["schemas"]["BacktestEquityCurve"];
            /**
             * Drawdown
             * @default []
             */
            drawdown: number[];
            /**
             * Daily Returns
             * @default []
             */
            daily_returns: number[];
            /**
             * Buy Hold Equity
             * @default []
             */
            buy_hold_equity: number[];
            /**
             * @default {
             *       "index": -1
             *     }
             */
            is_cutoff: components["schemas"]["IsCutoff"];
            /**
             * Metrics
             * @default {}
             */
            metrics: {
                [key: string]: unknown;
            };
            /** Is Metrics */
            is_metrics?: {
                [key: string]: unknown;
            } | null;
            /** Oos Metrics */
            oos_metrics?: {
                [key: string]: unknown;
            } | null;
            /**
             * Monthly Returns
             * @default {}
             */
            monthly_returns: {
                [key: string]: (number | null)[];
            };
            /**
             * Trades
             * @default []
             */
            trades: components["schemas"]["Trade"][];
            /**
             * Benchmark Annual Returns
             * @default {}
             */
            benchmark_annual_returns: {
                [key: string]: number;
            };
            regime_series?: components["schemas"]["RegimeSeries"] | null;
            /** Regime Breakdown */
            regime_breakdown?: {
                [key: string]: unknown;
            } | null;
            /** Source */
            source?: string | null;
            carry_adjusted?: components["schemas"]["CarryAdjusted"] | null;
            /** Params */
            params?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * BacktestEquityCurve
         * @description ``BacktestDetail.equity``: dates / values の配列ペア。
         */
        BacktestEquityCurve: {
            /**
             * Dates
             * @default []
             */
            dates: string[];
            /**
             * Values
             * @default []
             */
            values: number[];
        } & {
            [key: string]: unknown;
        };
        /**
         * BacktestSummary
         * @description ``GET /api/results`` リストの 1 件。
         */
        BacktestSummary: {
            /** Run Id */
            run_id: string;
            /** Strategy Id */
            strategy_id?: string | null;
            /** Symbol */
            symbol?: string | null;
            /** Run At */
            run_at?: string | null;
            /** Sharpe Ratio */
            sharpe_ratio?: number | null;
            /** Total Return Pct */
            total_return_pct?: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct?: number | null;
            /** Total Trades */
            total_trades?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * CarryAdjusted
         * @description --carry ランの carry_adjusted ブロック（vis#308）。
         */
        CarryAdjusted: {
            /** @default {} */
            metrics: components["schemas"]["CarryAdjustedMetrics"];
            /** Note */
            note?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * CarryAdjustedMetrics
         * @description FX キャリー（金利差近似）込みの参考メトリクス（vis#308）。
         *
         *     forge `backtest run --carry` の `_compute_equity_metrics` 出力に対応する。
         */
        CarryAdjustedMetrics: {
            /** Total Return Pct */
            total_return_pct?: number | null;
            /** Cagr Pct */
            cagr_pct?: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct?: number | null;
            /** Sharpe Ratio */
            sharpe_ratio?: number | null;
            /** Volatility Pct */
            volatility_pct?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * CliCheck
         * @description forge CLI の検出結果。version はおまけ情報（パース不能でも ok を保つ）。
         */
        CliCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "attention" | "unknown";
            /** Version */
            version?: string | null;
        };
        /**
         * ComparisonEquityCurve
         * @description ``StrategyComparison.equity`` の構造（dates / values の配列ペア）。
         */
        ComparisonEquityCurve: {
            /**
             * Dates
             * @default []
             */
            dates: string[];
            /**
             * Values
             * @default []
             */
            values: number[];
        } & {
            [key: string]: unknown;
        };
        /** ComponentVersion */
        ComponentVersion: {
            /**
             * Id
             * @enum {string}
             */
            id: "forge" | "visualizer" | "strike";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unknown" | "disabled";
            /** Current */
            current?: string | null;
            /** Latest */
            latest?: string | null;
            /**
             * Update Available
             * @default false
             */
            update_available: boolean;
            /**
             * Updatable
             * @default false
             */
            updatable: boolean;
            /** Message */
            message?: string | null;
            /** Code */
            code?: string | null;
            /** As Of */
            as_of?: string | null;
        };
        /** CreateAgentJobRequest */
        CreateAgentJobRequest: {
            /** Goal */
            goal: string;
            /** Symbol */
            symbol?: string | null;
            /**
             * Backend
             * @enum {string}
             */
            backend: "claude" | "codex";
            /** Max Turns */
            max_turns?: number | null;
            /** Base Strategy Id */
            base_strategy_id?: string | null;
        };
        /**
         * CreateDataJobRequest
         * @description `POST /api/data/jobs` のリクエスト（issue #485）。
         *
         *     値は forge CLI の argv にそのまま渡るため、境界でパターン検証して
         *     オプション注入・空白混入を塞ぐ（symbol 自体は build 側の ``--`` でも防護）。
         */
        CreateDataJobRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "fetch" | "update";
            /** Symbol */
            symbol?: string | null;
            /** Period */
            period?: string | null;
            /** Interval */
            interval?: string | null;
        };
        /** CreateJobRequest */
        CreateJobRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "backtest" | "optimize" | "wft";
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
            /** Trials */
            trials?: number | null;
            /** Windows */
            windows?: number | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CreateLiveJobRequest
         * @description `POST /api/live/jobs` のリクエスト。
         *
         *     現状 action は refresh のみ（forge `live refresh` への委譲）。パラメータは
         *     forge.yaml の `live.replay` が SSoT のため、リクエストには載せない。
         */
        CreateLiveJobRequest: {
            /**
             * Action
             * @constant
             */
            action: "refresh";
        };
        /**
         * DataCheck
         * @description 保有ヒストリカルデータの有無。
         */
        DataCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "attention" | "unknown";
            /** Count */
            count?: number | null;
        };
        /** DataListResponse */
        DataListResponse: {
            /** Datasets */
            datasets: components["schemas"]["DataSetItem"][];
            /** Count */
            count: number;
        };
        /**
         * DataSetItem
         * @description 保有データ 1 件。forge CLI の `--json` の `datasets[]` に鮮度を付加した形。
         */
        DataSetItem: {
            /** Symbol */
            symbol: string;
            /** Interval */
            interval: string;
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Rows */
            rows: number;
            /** Size Bytes */
            size_bytes: number;
            /** Updated At */
            updated_at?: string | null;
            /** Stale */
            stale?: boolean | null;
        };
        /** DuplicateStrategyRequest */
        DuplicateStrategyRequest: {
            /** New Strategy Id */
            new_strategy_id: string;
        };
        /** DuplicateStrategyResponse */
        DuplicateStrategyResponse: {
            /** Status */
            status: string;
            /** Strategy Id */
            strategy_id: string;
            /** Log Tail */
            log_tail?: string | null;
        };
        /**
         * EulaCheck
         * @description EULA 同意状態。GUI からは同意させない（CLI の対話に委ねる）。
         */
        EulaCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "attention" | "unknown";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 稼働確認 + バージョン確認用のレスポンス。
         *
         *     version はフッター表示・バグ報告時の確認に使う（UI から CLI に
         *     戻らずバージョンを確認できるようにする）。
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Forge Dir */
            forge_dir: string;
            /** Version */
            version: string;
        };
        /**
         * HistoricalResponse
         * @description OHLC 時系列のレスポンスエンベロープ。
         *
         *     `bars` 配列に加えて symbol / interval を返すことで、フロント側で
         *     複数 symbol のキャッシュを取り違えないよう識別子を付与する。
         */
        HistoricalResponse: {
            /** Symbol */
            symbol: string;
            /** Interval */
            interval: string;
            /** Bars */
            bars: components["schemas"]["OhlcBar"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * Idea
         * @description ideas.json の 1 アイデア。
         *
         *     フィールドは ideas.json のキーをそのまま反映。未知フィールドは
         *     透過するため ``extra="allow"`` を設定（運用での互換性維持）。
         */
        Idea: {
            /** Idea Id */
            idea_id?: string | null;
            /** Title */
            title?: string | null;
            /** Status */
            status?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Notes */
            notes?: string | null;
            /** Linked Strategies */
            linked_strategies?: string[] | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * IsCutoff
         * @description ``BacktestDetail.is_cutoff``: IS / OOS の境界位置。
         */
        IsCutoff: {
            /** Date */
            date?: string | null;
            /**
             * Index
             * @default -1
             */
            index: number;
        } & {
            [key: string]: unknown;
        };
        /** JobDetail */
        JobDetail: {
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error */
            error: string | null;
            /** Returncode */
            returncode: number | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Log Tail */
            log_tail: string | null;
        };
        /** JobSummary */
        JobSummary: {
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error */
            error: string | null;
        };
        /**
         * LiveAligned
         * @description ``LiveDetail.backtest.aligned``: 期間整合済みのバックテスト集計値。
         */
        LiveAligned: {
            /** Total Trades */
            total_trades: number;
            /** Win Rate Pct */
            win_rate_pct: number;
            /** Profit Factor */
            profit_factor: number;
            /** Max Drawdown Pct */
            max_drawdown_pct: number;
            /** Net Pnl */
            net_pnl: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveBacktest
         * @description ``LiveDetail.backtest``: 対応 backtest の run_id + period + aligned 集計。
         */
        LiveBacktest: {
            /** Run Id */
            run_id: string;
            period: components["schemas"]["LivePeriod"];
            aligned?: components["schemas"]["LiveAligned"] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveDetail
         * @description ``GET /api/live/{strategy_id}`` 詳細レスポンス。
         *
         *     live summary + 正規化済み trades と、それに整合する backtest aligned/diff、
         *     計算できなかった理由を伝える warnings 配列を返す。
         */
        LiveDetail: {
            /** Strategy Id */
            strategy_id: string;
            live: components["schemas"]["LiveSection"];
            backtest?: components["schemas"]["LiveBacktest"] | null;
            diff?: components["schemas"]["LiveDiff"] | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveDiff
         * @description ``LiveDetail.diff``: live − aligned のメトリクス差分。
         */
        LiveDiff: {
            /** Total Trades */
            total_trades?: number | null;
            /** Win Rate Pct */
            win_rate_pct?: number | null;
            /** Profit Factor */
            profit_factor?: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct?: number | null;
            /** Net Pnl */
            net_pnl?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveListItem
         * @description ``GET /api/live`` リストの 1 件。
         *
         *     ``kind`` は ``"strategy"``（trade 単位 / ``live_summaries``）または
         *     ``"position"``（combine portfolio / ``live_position_summaries``）。
         */
        LiveListItem: {
            /** Strategy Id */
            strategy_id: string;
            /** Has Summary */
            has_summary: boolean;
            /** Has Trades */
            has_trades: boolean;
            /** Kind */
            kind?: ("strategy" | "position") | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * LivePeriod
         * @description ``LiveDetail.live.period`` / ``LiveDetail.backtest.period``。
         */
        LivePeriod: {
            /** Start */
            start: string;
            /** End */
            end: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveSection
         * @description ``LiveDetail.live`` セクション (summary / trades / period)。
         */
        LiveSection: {
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /**
             * Trades
             * @default []
             */
            trades: components["schemas"]["LiveTrade"][];
            period?: components["schemas"]["LivePeriod"] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * LiveTrade
         * @description live trades JSON を正規化した 1 件。
         */
        LiveTrade: {
            /**
             * Trade Id
             * @default
             */
            trade_id: string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /** Side */
            side: string;
            /** Entry At */
            entry_at: string;
            /** Exit At */
            exit_at: string;
            /**
             * Qty
             * @default 0
             */
            qty: number;
            /**
             * Entry Price
             * @default 0
             */
            entry_price: number;
            /**
             * Exit Price
             * @default 0
             */
            exit_price: number;
            /**
             * Net Pnl
             * @default 0
             */
            net_pnl: number;
            /** Return Pct */
            return_pct?: number | null;
            /** Exit Reason */
            exit_reason?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * OhlcBar
         * @description 1 本のローソク足 (open / high / low / close + volume)。
         *
         *     `time` は ISO 8601 文字列（日足は ``YYYY-MM-DD``、intraday は
         *     ``YYYY-MM-DDTHH:MM:SS``）。`volume` は無いカラムの parquet では None。
         */
        OhlcBar: {
            /** Time */
            time: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * OptimizationHistoryEntry
         * @description ``StrategyDetail.optimization_history`` の 1 件。
         */
        OptimizationHistoryEntry: {
            /** Trial */
            trial: number;
            /** Best Sharpe */
            best_sharpe?: number | null;
            /** Run At */
            run_at?: string | null;
            /** N Trials */
            n_trials?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * OptimizeResult
         * @description ``GET /api/optimize/{strategy_id}`` レスポンス。
         */
        OptimizeResult: {
            /** Strategy Id */
            strategy_id: string;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /**
             * Run At
             * @default
             */
            run_at: string;
            /**
             * Metric Name
             * @default sharpe_ratio
             */
            metric_name: string;
            /** Best Metric */
            best_metric?: number | null;
            /** N Trials */
            n_trials?: number | null;
            /**
             * Trials
             * @default []
             */
            trials: components["schemas"]["OptimizeTrial"][];
            /**
             * Runs
             * @default []
             */
            runs: components["schemas"]["OptimizeRunSummary"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * OptimizeRunSummary
         * @description optimize run 切替 UI 用のメタ情報 1 件（issue #348）。
         */
        OptimizeRunSummary: {
            /** Run Id */
            run_id: string;
            /**
             * Run At
             * @default
             */
            run_at: string;
            /** N Trials */
            n_trials?: number | null;
            /**
             * Best Metric Name
             * @default sharpe_ratio
             */
            best_metric_name: string;
            /** Best Metric Value */
            best_metric_value?: number | null;
        };
        /**
         * OptimizeTrial
         * @description 1 試行のパラメータと評価値。
         *
         *     ``routers/optimize.py::_parse_trial`` が組み立てる dict の構造：
         *     ``{"params": {...}, "metric": float, "pass": bool, "metrics": {...}}``。
         *
         *     ``pass`` キーは Python 予約語のため明示フィールドとして宣言できない。
         *     レスポンス互換性のため ``extra="allow"`` で透過的に保持する。
         */
        OptimizeTrial: {
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: number;
            };
            /**
             * Metric
             * @default 0
             */
            metric: number;
            /**
             * Metrics
             * @default {}
             */
            metrics: {
                [key: string]: number;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * OrphanRunItem
         * @description 孤児 1 件。forge CLI の `--json` の `orphans[]` と 1:1 で対応する。
         */
        OrphanRunItem: {
            /** Strategy Id */
            strategy_id: string;
            /** Backtest Run Count */
            backtest_run_count: number;
            /** Optimization Run Count */
            optimization_run_count: number;
            /** Bytes */
            bytes: number;
            /** First Run At */
            first_run_at?: string | null;
            /** Last Run At */
            last_run_at?: string | null;
        };
        /** OrphanRunsResponse */
        OrphanRunsResponse: {
            /** Orphans */
            orphans: components["schemas"]["OrphanRunItem"][];
            /** Count */
            count: number;
            /** Total Bytes */
            total_bytes: number;
        };
        /**
         * Period
         * @description ``BacktestDetail.period``: equity 期間の YYYY-MM 表記。
         */
        Period: {
            /**
             * Start
             * @default
             */
            start: string;
            /**
             * End
             * @default
             */
            end: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * PineIndicatorSupport
         * @description 戦略が使う指標 1 件の Pine 対応状況（issue #488）。
         */
        PineIndicatorSupport: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Pine Supported */
            pine_supported: boolean;
        };
        /**
         * PineScriptResponse
         * @description 生成された Pine Script。
         *
         *     ``script`` は `alpha-forge pine preview` の stdout（Pine v6 本文）そのもの。
         *     ``filename`` はダウンロード時の推奨ファイル名（CLI の `pine generate` が
         *     書き出すファイル名と同じ規約）。
         */
        PineScriptResponse: {
            /** Strategy Id */
            strategy_id: string;
            /** Filename */
            filename: string;
            /** Script */
            script: string;
        };
        /**
         * PineSupportResponse
         * @description 生成前の非対応指標チェック結果（issue #488）。
         *
         *     対応表の SSoT は forge 側（`analyze indicator list --json`）。
         *     ``unsupported_types`` は重複を除いた昇順。``all_unsupported`` は指標を
         *     1 つ以上持ち、そのすべてが Pine 非対応（= 生成しても TradingView で
         *     機能しない可能性が高い）ことを示す。
         */
        PineSupportResponse: {
            /** Strategy Id */
            strategy_id: string;
            /** Indicators */
            indicators: components["schemas"]["PineIndicatorSupport"][];
            /** Unsupported Types */
            unsupported_types: string[];
            /** All Unsupported */
            all_unsupported: boolean;
        };
        /** PruneOrphansRequest */
        PruneOrphansRequest: {
            /** Strategy Ids */
            strategy_ids: string[];
        };
        /** PruneOrphansResponse */
        PruneOrphansResponse: {
            /** Deleted Strategy Ids */
            deleted_strategy_ids: string[];
            /** Deleted Backtest Rows */
            deleted_backtest_rows: number;
            /** Deleted Optimization Rows */
            deleted_optimization_rows: number;
            /** Reclaimed Bytes */
            reclaimed_bytes: number;
            /** Vacuum Error */
            vacuum_error?: string | null;
        };
        /**
         * RegimeSeries
         * @description HMM レジームステート時系列。``services.shape_regime_series`` で正規化済み。
         *
         *     すべてのフィールドは ``services`` 側で検証済み（dates と states の長さ一致、
         *     states は int リスト等）なので、Pydantic 側では shape のみを担保する。
         */
        RegimeSeries: {
            /** Dates */
            dates: string[];
            /** States */
            states: number[];
            /** N States */
            n_states: number;
            /** Label Names */
            label_names?: {
                [key: string]: string;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** RunBacktestRequest */
        RunBacktestRequest: {
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
        };
        /** RunBacktestResponse */
        RunBacktestResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Log Tail */
            log_tail?: string | null;
        };
        /** SaveParametersRequest */
        SaveParametersRequest: {
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
        };
        /** SaveParametersResponse */
        SaveParametersResponse: {
            /** Status */
            status: string;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Log Tail */
            log_tail?: string | null;
        };
        /** SetupStatusResponse */
        SetupStatusResponse: {
            /** Ready */
            ready: boolean;
            cli: components["schemas"]["CliCheck"];
            eula: components["schemas"]["EulaCheck"];
            workspace: components["schemas"]["WorkspaceCheck"];
            auth: components["schemas"]["AuthCheck"];
            data: components["schemas"]["DataCheck"];
        };
        /**
         * SparklineResponse
         * @description Browse 行ホバー用の軽量 sparkline (issue #387)。
         *
         *     最新 run の equity をダウンサンプルした値だけを返し、
         *     2MB 級のフル詳細を引かずに済ませる。
         */
        SparklineResponse: {
            /** Run Id */
            run_id: string;
            /** Values */
            values: number[];
        };
        /**
         * StrategyComparison
         * @description ``GET /api/strategies/compare`` の 1 件。equity / 比較指標を含む。
         */
        StrategyComparison: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /**
             * Total Return Pct
             * @default 0
             */
            total_return_pct: number;
            /**
             * Cagr Pct
             * @default 0
             */
            cagr_pct: number;
            /**
             * Sharpe Ratio
             * @default 0
             */
            sharpe_ratio: number;
            /**
             * Sortino Ratio
             * @default 0
             */
            sortino_ratio: number;
            /**
             * Max Drawdown Pct
             * @default 0
             */
            max_drawdown_pct: number;
            /**
             * Win Rate Pct
             * @default 0
             */
            win_rate_pct: number;
            /**
             * Profit Factor
             * @default 0
             */
            profit_factor: number;
            /**
             * Total Trades
             * @default 0
             */
            total_trades: number;
            /**
             * Is Baseline
             * @default false
             */
            is_baseline: boolean;
            /**
             * @default {
             *       "dates": [],
             *       "values": []
             *     }
             */
            equity: components["schemas"]["ComparisonEquityCurve"];
            /**
             * Daily Returns
             * @default []
             */
            daily_returns: number[];
        } & {
            [key: string]: unknown;
        };
        /**
         * StrategyDetail
         * @description ``GET /api/strategies/{strategy_id}`` 詳細レスポンス。
         *
         *     戦略定義（parameters / indicators / variables / *_conditions /
         *     risk_management / regime_config）と、バックテスト履歴 / 最適化履歴を返す。
         */
        StrategyDetail: {
            /** Strategy Id */
            strategy_id: string;
            /** Name */
            name: string;
            /**
             * Parameters
             * @default {}
             */
            parameters: {
                [key: string]: unknown;
            };
            /**
             * Indicators
             * @default []
             */
            indicators: unknown[];
            /**
             * Variables
             * @default []
             */
            variables: unknown[];
            /** Entry Conditions */
            entry_conditions?: unknown;
            /** Exit Conditions */
            exit_conditions?: unknown;
            /** Risk Management */
            risk_management?: unknown;
            /** Regime Config */
            regime_config?: unknown;
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["StrategyResultEntry"][];
            /**
             * Optimization History
             * @default []
             */
            optimization_history: components["schemas"]["OptimizationHistoryEntry"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * StrategyResultEntry
         * @description ``StrategyDetail.results`` の 1 件（バックテスト履歴サマリ）。
         */
        StrategyResultEntry: {
            /** Run Id */
            run_id: string;
            /** Symbol */
            symbol?: string | null;
            /** Sharpe */
            sharpe?: number | null;
            /** Return Pct */
            return_pct?: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct?: number | null;
            /** Total Trades */
            total_trades?: number | null;
            /** Run At */
            run_at?: string | null;
            /** Source */
            source?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * StrategySummary
         * @description ``GET /api/strategies`` リストの 1 件。
         */
        StrategySummary: {
            /** Strategy Id */
            strategy_id: string;
            /** Name */
            name: string;
            /** Symbol */
            symbol?: string | null;
            /** Timeframe */
            timeframe?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Target Symbols
             * @default []
             */
            target_symbols: string[];
            /** Latest Sharpe */
            latest_sharpe?: number | null;
            /** Latest Return Pct */
            latest_return_pct?: number | null;
            /** Latest Max Drawdown Pct */
            latest_max_drawdown_pct?: number | null;
            /** Latest Profit Factor */
            latest_profit_factor?: number | null;
            /** Latest Win Rate Pct */
            latest_win_rate_pct?: number | null;
            /** Latest Total Trades */
            latest_total_trades?: number | null;
            /** Last Run At */
            last_run_at?: string | null;
            /** Latest Source */
            latest_source?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Trade
         * @description ``BacktestDetail.trades`` の 1 件。
         *
         *     ``exit_price`` / ``sl_price`` / ``tp_price`` は TradingView lightweight-charts
         *     の markers / priceLine 表示用に追加されたフィールド (#189)。
         *     alpha-forge 側が値を出力していない場合 ``None`` のままになる。
         */
        Trade: {
            /** Id */
            id: number | string;
            /** Direction */
            direction: string;
            /**
             * Entry Date
             * @default
             */
            entry_date: string;
            /**
             * Exit Date
             * @default
             */
            exit_date: string;
            /**
             * Entry Price
             * @default 0
             */
            entry_price: number;
            /** Exit Price */
            exit_price?: number | null;
            /** Sl Price */
            sl_price?: number | null;
            /** Tp Price */
            tp_price?: number | null;
            /**
             * Return Pct
             * @default 0
             */
            return_pct: number;
            /**
             * Pnl
             * @default 0
             */
            pnl: number;
            /**
             * Holding Days
             * @default 0
             */
            holding_days: number;
            /**
             * Mae Pct
             * @default 0
             */
            mae_pct: number;
            /**
             * Mfe Pct
             * @default 0
             */
            mfe_pct: number;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionsResponse */
        VersionsResponse: {
            /** Components */
            components: components["schemas"]["ComponentVersion"][];
        };
        /**
         * WFOResponse
         * @description ``GET /api/wfo/{strategy_id}`` レスポンス。
         */
        WFOResponse: {
            /** Strategy Id */
            strategy_id: string;
            /**
             * Strategy Name
             * @default
             */
            strategy_name: string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /**
             * Metric Name
             * @default sharpe_ratio
             */
            metric_name: string;
            /**
             * Windows
             * @default []
             */
            windows: components["schemas"]["WFOWindow"][];
            /**
             * Composite Equity
             * @default []
             */
            composite_equity: number[];
            /**
             * Composite Dates
             * @default []
             */
            composite_dates: string[];
        } & {
            [key: string]: unknown;
        };
        /**
         * WFOWindow
         * @description 1 ウィンドウの IS / OOS 評価値。
         *
         *     ``pass`` キーは Python 予約語のため明示フィールドとして宣言できない。
         *     レスポンス互換性のため ``extra="allow"`` で透過的に保持する。
         */
        WFOWindow: {
            /** Id */
            id: number;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Is Start
             * @default
             */
            is_start: string;
            /**
             * Is End
             * @default
             */
            is_end: string;
            /**
             * Oos Start
             * @default
             */
            oos_start: string;
            /**
             * Oos End
             * @default
             */
            oos_end: string;
            /**
             * Is Sharpe
             * @default 0
             */
            is_sharpe: number;
            /**
             * Oos Sharpe
             * @default 0
             */
            oos_sharpe: number;
            /**
             * Is Return
             * @default 0
             */
            is_return: number;
            /**
             * Oos Return
             * @default 0
             */
            oos_return: number;
            /**
             * Oos Is Ratio
             * @default 0
             */
            oos_is_ratio: number;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: number;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * WorkspaceCheck
         * @description workspace（forge.yaml / FORGE_CONFIG）の解決状態。
         */
        WorkspaceCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "attention" | "unknown";
            /** Config Path */
            config_path?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_results_api_results_get: {
        parameters: {
            query?: {
                strategy_id?: string | null;
                since?: string | null;
                /** @description 返す最大件数（省略時は全件・従来互換） */
                limit?: number | null;
                /** @description 読み飛ばす件数 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_results__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategySummary"][];
                };
            };
        };
    };
    compare_strategies_api_strategies_compare_get: {
        parameters: {
            query: {
                /** @description カンマ区切りの strategy_id */
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyComparison"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_sparkline_api_strategies__strategy_id__sparkline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SparklineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_api_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_strategy_parameters_api_strategies__strategy_id__parameters_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveParametersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveParametersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_strategy_api_strategies__strategy_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateStrategyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateStrategyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ideas_api_ideas_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Idea"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_idea_api_ideas__idea_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idea_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Idea"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wfo_api_wfo__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WFOResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_optimize_api_optimize__strategy_id__get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_backtest_api_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunBacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_live_api_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveListItem"][];
                };
            };
        };
    };
    get_live_api_live__strategy_id__get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_live_job_api_live_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLiveJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_historical_api_historical__symbol__get: {
        parameters: {
            query?: {
                interval?: string;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataListResponse"];
                };
            };
        };
    };
    create_data_job_api_data_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDataJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_pine_api_pine__strategy_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PineScriptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pine_support_api_pine__strategy_id__support_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PineSupportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orphan_runs_api_maintenance_orphan_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrphanRunsResponse"];
                };
            };
        };
    };
    prune_orphan_runs_api_maintenance_orphan_runs_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PruneOrphansRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PruneOrphansResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_backends_api_agent_backends_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentBackendsResponse"];
                };
            };
        };
    };
    create_agent_job_api_agent_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_setup_status_api_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
        };
    };
    get_versions_api_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionsResponse"];
                };
            };
        };
    };
    update_forge_api_versions_forge_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
        };
    };
    update_strike_api_versions_strike_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_visualizer_api_versions_visualizer_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
